name = "documentation-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "documentation"
database_id = "aba7ed26-dafa-4f29-b8a6-892c54a8b239"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "documentation"

[vars]
# Comma-separated list of email addresses that can access the /admin panel.
# These must match the "preferred_username" claim from the Microsoft ID token.
ADMIN_EMAILS = ""
